version: '3'

services:
  # Redis sever for application cache
  cache:
    container_name: ${APP_NAME}_redis
    image: redis
    expose:
      - 6379
    volumes:
      - cacheStorage:/data
    networks:
      - backend
    command: redis-server --requirepass ${REDIS_PASSWORD}
    
  # Redis explorer for application
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 32541:8001
    volumes:
      - cacheStorage:/db
    networks:
      - frontend
      - backend
    depends_on:
      - cache
    
  # MariaDB master database for application storage
  masterdb:
    container_name: ${APP_NAME}_write
    image: bitnami/mariadb:10.3
    volumes:
      - dbMasterStorage:/bitnami/mariadb
    expose:
      - 3306
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=T0PSc0r3r
      - MARIADB_USER=topscorer
      - MARIADB_PASSWORD=T0PSc0r3r@!
      - MARIADB_DATABASE=topscorer
    networks:
      - backend
  # MariaDB slave database for application storage
  slavedb:
    container_name: ${APP_NAME}_read
    image: bitnami/mariadb:10.3
    volumes:
      - dbSlaveStorage:/bitnami/mariadb
    expose:
      - 3306
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=masterdb
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=T0PSc0r3r
      - MARIADB_USER=topscorer
      - MARIADB_PASSWORD=T0PSc0r3r@!
      - MARIADB_DATABASE=topscorer
    networks:
      - backend
    depends_on:
      - masterdb

  web:
    container_name: ${APP_NAME}
    tty: true
    build:
      context: ./
    ports:
      - 80:8080
    volumes:
      - apilogStorage:/var/log
      - ./:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - cache
      - masterdb
      - slavedb

  # PhpMyAdmin for MariaDB servers management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 32540:80
    environment:
      - PMA_HOSTS=masterdb,slavedb
      # Remove below user and password env var for production.
      - PMA_USER=root
      - PMA_PASSWORD=T0PSc0r3r
    depends_on:
      - masterdb
      - slavedb
    networks:
      - frontend
      - backend

volumes:
  apilogStorage: {}
  cacheStorage: {}
  dbMasterStorage: {}
  dbSlaveStorage: {}

networks:
  frontend:
  backend:
